### ISSUE TITLE
チュートリアルの文字が正しく表示されない

### ISSUE THREAD

**Issue by Raclamusi** [tyanmahou/ColorfulTone#45]
### 要点

ColorfulTone-4.0.0/Resource/Sample/tutorial/tutorial.csv が Shift_JIS です。

### 発生している問題

タイトル画面からチュートリアルを始めたとき、文字（特に日本語）が正しく表示されません。

### 発生原因

`ct::TutorialScene` で読み込まれる Resource/Sample/tutorial/tutorial.csv の文字コードが Shift_JIS であることが原因と考えられます。

### スクリーンショット

![スクリーンショット](https://github.com/tyanmahou/ColorfulTone/assets/61970673/21c99f55-8a61-4585-bb51-78243af7deb7)

**Comment by tyanmahou** [comment]
あざます！！対処漏れだったかも

**Comment by tyanmahou** [comment]
なぜかリリースパッケージにだけエンコード修正前のものが入っていました
発見ありがとうございます
