### ISSUE TITLE
リザルト画面から戻るキーが表示と異なる

### ISSUE THREAD

**Issue by Raclamusi** [tyanmahou/ColorfulTone#46]
### 発生している問題

リザルト画面で、画面右下に `[Enter]戻る [BackSpace]戻る` と表示されますが、 <kbd>Backspace</kbd> を押しても何も起こりません。

### 発生原因

`ct::ResultScene::update()` で <kbd>Backspace</kbd> ( `PlayKey::SmallBack()` ) の判定が含まれていません。

https://github.com/tyanmahou/ColorfulTone/blob/84a4468338657f65c770b3b9824851cde800e528/System/scenes/Scene/Result/ResultScene.cpp?ts=4#L193-L199

**Comment by tyanmahou** [comment]
thanks

**Comment by tyanmahou** [comment]
修正しました。
報告ありがとうございます。
